spring:
  application:
    name: ControlBackendbf
  datasource:
    url: jdbc:postgresql://${DB_HOST:db}:${DB_PORT:5432}/${DB_NAME:app_db}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none    # Liquibase Ã¼bernimmt
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

# OpenAPI / Swagger-UI (springdoc)
springdoc:
  api-docs:
    enabled: true   # -> http://localhost:8080/api/docs
  swagger-ui:
    enabled: true   # -> http://localhost:8080/swagger-ui